<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro"  name="robot">

    <xacro:property name="camera_m" value="0.2" /> 
    <xacro:property name="camera_x" value="0.05" />
    <xacro:property name="camera_y" value="0.1" />
    <xacro:property name="camera_z" value="0.02" />

    <joint name="camera_joint" type="fixed">
        <parent link="chassis"/>
        <child link="camera_frame"/>
        <origin xyz="${chassis_x/2} 0 ${chassis_h+3*camera_z}" rpy="0 0 0"/>
    </joint>

    <link name="camera_frame">
        <xacro:inertial_box mass="${camera_m}" x="${camera_x}" y="${camera_y}" z="${camera_z}">
            <origin xyz="0.0 0.0 0" rpy="0 0 0"/>
        </xacro:inertial_box>
        <visual>
            <origin xyz="0.0 0.0 0.0" rpy="0 0 0"/>
            <geometry>
                <box size="${camera_x} ${camera_y} ${camera_z}"/>
            </geometry>
            <material name="red">
                <color rgba="1 0 0 1"/>
            </material>
        </visual>
        <collision>
            <origin xyz="0.0 0.0 0.0" rpy="0 0 0"/>
            <geometry>
                <box size="${camera_x} ${camera_y} ${camera_z}"/>
            </geometry>
        </collision>
    </link>

    <gazebo reference="camera_frame">
        <material>Gazebo/Black</material>
        <sensor name="camera" type="camera">
            <pose> 0 0 0 0 0 0 </pose>
            <visualize>true</visualize>
            <update_rate>10</update_rate>
            <camera>
                <horizontal_fov>1.089</horizontal_fov>
                <image>
                    <format>R8G8B8</format>
                    <width>640</width>
                    <height>480</height>
                </image>
                <clip>
                    <near>0.05</near>
                    <far>8.0</far>
                </clip>
            </camera>
            <plugin name="camera_controller" filename="libgazebo_ros_camera.so">
                <frame_name>camera_frame</frame_name>
            </plugin>
        </sensor>
    </gazebo>

</robot>